### ISSUE TITLE
There is no data holder converter registered to convert from a class net.kyori.adventure.nbt.api.BinaryTagHolderImpl instance to a interface net.kyori.adventure.text.serializer.gson.GsonDataComponentValue (on field minecraft:lore)

### ISSUE THREAD

**Issue by that-apex** [KyoriPowered/adventure#1130]
`GsonComponentSerializer` will fail to serialize an ItemStack that has components if it was previously deserialized with minimessage.
```kotlin
val item = ItemStack(Material.DIAMOND)
item.editMeta { it.lore(listOf(Component.text("my lore"))) }
val baseComponent = Component.translatable(item).hoverEvent(item.asHoverEvent())

val json1 = GsonComponentSerializer.gson().serialize(baseComponent) // fine
println(json1)

try {
    val reserialized = MiniMessage.miniMessage().deserialize(MiniMessage.miniMessage().serialize(baseComponent))
    GsonComponentSerializer.gson().serialize(reserialized)
} catch (e: Exception) {
    e.printStackTrace()
}
```
results in
```
{"hoverEvent":{"action":"show_item","contents":{"id":"minecraft:diamond","count":1,"components":{"minecraft:lore":["\"my lore\""]}}},"translate":"item.minecraft.diamond"}
java.lang.IllegalArgumentException: There is no data holder converter registered to convert from a class net.kyori.adventure.nbt.api.BinaryTagHolderImpl instance to a interface net.kyori.adventure.text.serializer.gson.GsonDataComponentValue (on field minecraft:lore)
	at net.kyori.adventure.text.event.DataComponentValueConverterRegistry.convert(DataComponentValueConverterRegistry.java:90)
	at net.kyori.adventure.text.event.HoverEvent$ShowItem.dataComponentsAs(HoverEvent.java:623)
	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:139)
	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:49)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196)
	at com.google.gson.Gson.toJson(Gson.java:842)
	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:296)
	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:62)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196)
	at com.google.gson.Gson.toJson(Gson.java:842)
	at com.google.gson.Gson.toJsonTree(Gson.java:712)
	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:252)
	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:196)
	at com.google.gson.Gson.toJson(Gson.java:842)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:759)
	at com.google.gson.Gson.toJson(Gson.java:736)
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:104)
	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:41)
```

**Comment by zml2008** [comment]
What platform are you using? And which version? I believe some of the SNBT conversion glue is platform-level.

**Comment by that-apex** [comment]
Latest stable Paper build.
`This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)`

**Comment by zml2008** [comment]
Are you using adventure-platform? Or a native impl?

**Comment by that-apex** [comment]
Just the implementation that comes with paper.

**Comment by zml2008** [comment]
Looks like this is something that's easier to fix in Paper, see referenced issue.

**Comment by kangarko** [comment]
@zml2008 This is still happening on the latest paper (1.21.4-114-main@cd9d6d6 (2025-01-15T11:21:28Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)):

````
[13:36:47 WARN]: java.lang.IllegalArgumentException: There is no data holder converter registered to convert from a class net.kyori.adventure.nbt.api.BinaryTagHolderImpl instance to a interface net.kyori.adventure.text.serializer.gson.GsonDataComponentValue (on field minecraft:banner_patterns)
[13:36:47 WARN]: 	at net.kyori.adventure.text.event.DataComponentValueConverterRegistry.convert(DataComponentValueConverterRegistry.java:90)
[13:36:47 WARN]: 	at net.kyori.adventure.text.event.HoverEvent$ShowItem.dataComponentsAs(HoverEvent.java:623)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:151)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:50)
[13:36:47 WARN]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[13:36:47 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:310)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:64)
[13:36:47 WARN]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[13:36:47 WARN]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[13:36:47 WARN]: 	at com.google.gson.Gson.toJsonTree(Gson.java:802)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:252)
[13:36:47 WARN]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77)
````

The message caused this is:

`I hold <hover:show_item:black_banner:16:banner_patterns:'[{color:"red",pattern:"minecraft:bricks"},{color:"red",pattern:"minecraft:stripe_middle"},{color:"blue",pattern:"minecraft:gradient_up"}]'>[16x Black Banner]</gray></white></yellow></gray></hover></white><hover:show_text:'flpm_8d2e240a-e488-48e1-b799-23feffe1e49b flps_1e2ec7e8-16c8-3f2b-aec4-a96365713061'>
`

**Comment by kangarko** [comment]
Let me know what data you need to be able to reproduce this bug.

**Comment by zml2008** [comment]
Again, this is a platform issue, tracking tickets for several platforms are linked in the history above.

**Comment by kangarko** [comment]
Okay sorry, just to confirm you meant this? https://github.com/PaperMC/Paper/issues/11768

**Comment by kangarko** [comment]
Posted there hopefully it's the right place
