### ISSUE TITLE
Gson deserialize | ComponentSerializerImpl don't know how to turn $.style into a Component

### ISSUE THREAD

**Issue by IvanNovR** [KyoriPowered/adventure#1135]
### To reproduce:
1. Serialize a List<Map<>> with a net.kyori.adventure.text.Component inside using Serializer.serialize(List<Map<String, Object>> list);
2. Try to deserialize using Serializer.deserialize(String json);
3. And you will get stacktrace;

### Stacktrace:
<details>

```
[01:27:08 ERROR]: Could not pass event PrepareAnvilEvent to ItemDecorations v1.1
com.google.gson.JsonParseException: Don't know how to turn $.style into a Component
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:337) ~[adventure-text-serializer-gson-4.17.0.jar:?]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:221) ~[adventure-text-serializer-gson-4.17.0.jar:?]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:77) ~[adventure-text-serializer-gson-4.17.0.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:89) ~[adventure-text-serializer-gson-4.17.0.jar:?]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:41) ~[adventure-text-serializer-gson-4.17.0.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.utils.serializers.adapters.ComponentAdapter.deserialize(ComponentAdapter.java:36) ~[LoreApi-1.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.utils.serializers.adapters.ComponentAdapter.deserialize(ComponentAdapter.java:10) ~[LoreApi-1.1.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.utils.serializers.adapters.LoreListAdapter.deserialize(LoreListAdapter.java:31) ~[LoreApi-1.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.utils.serializers.adapters.LoreListAdapter.deserialize(LoreListAdapter.java:13) ~[LoreApi-1.1.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1014) ~[gson-2.10.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.utils.serializers.Serializer.deserialize(Serializer.java:28) ~[LoreApi-1.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.LoreApi.createLoreModifier(LoreApi.java:47) ~[LoreApi-1.1.jar:?]
        at LoreApi-1.1.jar/ru.dreamscape.loreapi.LoreApi.getLoreModifier(LoreApi.java:41) ~[LoreApi-1.1.jar:?]
        at ItemDecorations-1.1.jar/ru.dreamscape.itemdecorations.events.NameAndStory.makeWithStory(NameAndStory.java:60) ~[ItemDecorations-1.1.jar:?]
        at ItemDecorations-1.1.jar/ru.dreamscape.itemdecorations.events.NameAndStory.onPrepareAnvilName(NameAndStory.java:79) ~[ItemDecorations-1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor410.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1818) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.inventory.AnvilMenu.setItemName(AnvilMenu.java:331) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleRenameItem(ServerGamePacketListenerImpl.java:1013) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundRenameItemPacket.handle(ServerboundRenameItemPacket.java:33) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundRenameItemPacket.handle(ServerboundRenameItemPacket.java:15) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
``` 
</details>

### Json on which stacktrace occurs
```json
{"content":"ABC","children":[],"style":{"decorations":{"obfuscated":"NOT_SET","bold":"NOT_SET","strikethrough":"NOT_SET","underlined":"NOT_SET","italic":"FALSE"}}}
```

### My source code:
<details>
  <summary>public class Serializer</summary>
  
  ```java
  public class Serializer {
      private static final Gson gson = new GsonBuilder()
              .registerTypeAdapter(Component.class, new ComponentAdapter())
              .registerTypeAdapter(new TypeToken<List<Map<String, Object>>>() {}.getType(), new LoreListAdapter())
              .create();
      private static final Type LORE_LIST_TYPE = new TypeToken<List<Map<String, Object>>>() {}.getType();
  
      public static String serialize(List<Map<String, Object>> list) {
          return gson.toJson(list, LORE_LIST_TYPE);
      }
  
      public static List<Map<String, Object>> deserialize(String json) {
          return gson.fromJson(json, LORE_LIST_TYPE);
      }
  }
  ``` 
</details>
<details>
  <summary>public class LoreListAdapter</summary>

  ```java
  public class LoreListAdapter implements JsonDeserializer<List<Map<String, Object>>>  {
      @Override
      public List<Map<String, Object>> deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
          List<Map<String, Object>> resultList = new ArrayList<>();
  
          JsonArray jsonArray = json.getAsJsonArray();
          for (JsonElement element : jsonArray) {
              JsonObject jsonObject = element.getAsJsonObject();
              Map<String, Object> map = new HashMap<>();
  
              if (jsonObject.has("component")) {
                  Component component = context.deserialize(jsonObject.get("component"), Component.class);
                  map.put("component", component);
              }
  
              for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
                  if (!"align".equals(entry.getKey()) && !"component".equals(entry.getKey())) {
                      map.put(entry.getKey(), context.deserialize(entry.getValue(), Object.class));
                  }
              }
  
              resultList.add(map);
          }
          return resultList;
      }
  }
  ```
</details>
<details>
  <summary>public class ComponentAdapter</summary>

  ```java
  public class ComponentAdapter implements JsonSerializer<Component>, JsonDeserializer<Component> {
      @Override
      public Component deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
          Bukkit.getConsoleSender().sendMessage(json.toString());
  
          if (json.isJsonPrimitive() && json.getAsJsonPrimitive().isString()) {
              return GsonComponentSerializer.gson().deserialize(json.getAsString());
          } else if (json.isJsonObject()) {
              return GsonComponentSerializer.gson().deserialize(json.toString());
          } else {
              throw new JsonParseException("Unexpected JSON format for Component: " + json);
          }
      }
      @Override
      public JsonElement serialize(Component src, Type typeOfSrc, JsonSerializationContext context) {
          JsonElement json = new JsonPrimitive(GsonComponentSerializer.gson().serialize(src));
          Bukkit.getConsoleSender().sendMessage(json.toString());
          return json;
      }
  }
  ```
</details>

### Versions:

- Pufferfish version 1.21.1-21-HEAD@cfa3c61 (2024-10-22T23:08:19Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
- adventureVersion = "4.17.0"

**Comment by zml2008** [comment]
That json is malformed for the component structure, this is an issue with your incorrect usage of Gson, not an adventure issue.
