### ISSUE TITLE
UnsupportedOperationException while deserialize gson hoverEvent

### ISSUE THREAD

**Issue by ForceUpdate1** [KyoriPowered/adventure#216]
Message:
```
[15:08:23 ERROR]: INFORMATION: {"text":"","extra":[{"text":""},{"text":"[","color":"dark_gray"},{"text":"Skyblock","color":"gold"},{"text":"] ","color":"dark_gray"},{"text":"","color":"gray"},{"text":"TheJana","color":"aqua"},{"text":" hat in deinem Shop ","color":"gray"},{"text":"1x ","color":"green","hoverEvent":{"action":"show_item","value":[{"text":"{DataVersion:2580,id:\"minecraft:emerald\",tag:{display:{Name:\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"Spielershop\"}],\"text\":\"\"}\u0027,Lore:[\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"In Shops kannst du Gegenstände\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"anderen Spielern zum Kauf anbieten.\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"green\",\"text\":\"Rechtsklick \"},{\"italic\":false,\"color\":\"red\",\"text\":\"» \"},{\"italic\":false,\"color\":\"gray\",\"text\":\"Platziert den Shop.\"}],\"text\":\"\"}\u0027]}},Count:1b}"}]}},{"text":"GEGENSTAND","color":"gold","bold":true,"italic":true,"hoverEvent":{"action":"show_item","value":[{"text":"{DataVersion:2580,id:\"minecraft:emerald\",tag:{display:{Name:\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gold\",\"text\":\"Spielershop\"}],\"text\":\"\"}\u0027,Lore:[\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"In Shops kannst du Gegenstände\"}],\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"gray\",\"text\":\"anderen Spielern zum Kauf anbieten.\"}],\"text\":\"\"}\u0027,\u0027{\"text\":\"\"}\u0027,\u0027{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"green\",\"text\":\"Rechtsklick \"},{\"italic\":false,\"color\":\"red\",\"text\":\"» \"},{\"italic\":false,\"color\":\"gray\",\"text\":\"Platziert den Shop.\"}],\"text\":\"\"}\u0027]}},Count:1b}"}]}},{"text":" für ","color":"gray"},{"text":"23.000,00 Taler","color":"gold"},{"text":" gekauft.","color":"gray"}]}
```

Exception:
```
[15:08:23 ERROR]: java.lang.UnsupportedOperationException
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:172)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:134)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:76)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:51)
[15:08:23 ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:932)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:1003)
[15:08:23 ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:157)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:153)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:73)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:54)
[15:08:23 ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:932)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:897)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:846)
[15:08:23 ERROR]: at com.google.gson.Gson.fromJson(Gson.java:817)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:83)
[15:08:23 ERROR]: at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:40)
[15:08:23 ERROR]: at de.cytooxien.enderman.network.bootstrap.packet.PacketManager.callListeners(PacketManager.java:214)
[15:08:23 ERROR]: at de.cytooxien.enderman.network.bootstrap.packet.PacketManager.lambda$handleIncomingPacket$3(PacketManager.java:168)
[15:08:23 ERROR]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:08:23 ERROR]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```

The message was created with the bungeecord-chat component builder

https://github.com/KyoriPowered/adventure/blob/474ea3b7911a457e65daf50ed7eb57c13e957739/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java#L172

**Comment by astei** [comment]
This appears to be intentional, you need to provide a `LegacyHoverEventSerializer` to the Gson component serializer builder to deserialize "legacy" hover events. It appears BungeeCord's chat API still produces them.

You can find potentially acceptable implementations in [adventure-platform](https://github.com/KyoriPowered/adventure-platform/blob/304e67a0385e72b1987a1bf6917b49a1ed135234/text-serializer-craftbukkit/src/main/java/net/kyori/adventure/text/serializer/craftbukkit/NBTLegacyHoverEventSerializer.java) or [Velocity](https://github.com/VelocityPowered/Velocity/blob/e3f17eeb245b8d570f16c1f2aff5e7eafb698d5e/proxy/src/main/java/com/velocitypowered/proxy/protocol/util/VelocityLegacyHoverEventSerializer.java), though I think Adventure should provide a default implementation. @kashike any thoughts?
