### ISSUE TITLE
StringIndexOutOfBoundsException when parsing malformed hex colors

### ISSUE THREAD

**Issue by TheBusyBiscuit** [KyoriPowered/adventure#266]
# Description
When deserializing legacy text that contains hex-colors, a malformed hex color input will result in a `StringIndexOutOfBoundsException`.
Normally this wouldn't be a problem, however in mcMMO this text format is applied onto user input, which can result in player input causing these exceptions.

For more info about the original issue, see: https://github.com/mcMMO-Dev/mcMMO/issues/4404 and https://github.com/mcMMO-Dev/mcMMO/issues/4403

## Code to reproduce this
I was able to reproduce this issue in a clean environment with nothing but Adventure.

```java
    public static void main(String[] args) {
        LegacyComponentSerializer serializer = LegacyComponentSerializer.builder()
                .hexColors()
                .character('&')
                .hexCharacter('#')
                .build();

        String text = "&#121212Hello";
        String text2 = "&#121212&#000000fd&#dsds";
        String text3 = "&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33";
        
        testString(serializer, text);
        testString(serializer, text2);
        testString(serializer, text3);
    }

    private static void testString(LegacyComponentSerializer serializer, String text) {
        try {
            logger.log(Level.INFO, "Deserializing: {0}", text);
            logger.log(Level.INFO, "Result: {0}", serializer.deserialize(text));
        }
        catch(Exception x) {
            x.printStackTrace();
        }
    }
```

This was the result when calling `LegacyComponentSerializer#deserialize()`
```
Deserializing: &#121212Hello
Result: TextComponentImpl{content="Hello", children=[], style=StyleImpl{color=TextColorImpl{value="#121212"}, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}}

Deserializing: &#121212&#000000fd&#dsds
java.lang.StringIndexOutOfBoundsException: String index out of range: 26
	at java.lang.String.substring(String.java:1963)
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.decodeTextFormat(LegacyComponentSerializerImpl.java:152)
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:217)

Deserializing: &#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33ff8ea&#84ff33b&#33
java.lang.StringIndexOutOfBoundsException: String index out of range: 260
	at java.lang.String.substring(String.java:1963)
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.decodeTextFormat(LegacyComponentSerializerImpl.java:152)
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:217)

```

## Versions that were used
```xml
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-api</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-api</artifactId>
            <version>4.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bukkit</artifactId>
            <version>4.0.0-SNAPSHOT</version>
        </dependency>
```

**Comment by TheBusyBiscuit** [comment]
Thanks! ❤️
