### ISSUE TITLE
Problem with ViaVersion and sending message

### ISSUE THREAD

**Issue by P3ridot** [KyoriPowered/adventure#341]
I use adventure (I think latest release, 4.0.0-SNAPSHOT) (relocated but I think it doesn't changes a lot) weird problem occurs. I have server on Paper 1.12.2 and ViaVersion 3.2.1. When player version is 1.16 or higher that error shows in console.
```[22:00:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lang' in plugin TitanMessages v1.1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoSuchMethodError: us.myles.ViaVersion.api.PacketWrapper.<init>(ILnet/titanvale/titanapi/libs/netty/buffer/ByteBuf;Lus/myles/ViaVersion/api/data/UserConnection;)V
        at net.titanvale.titanapi.libs.kyori.adventure.platform.viaversion.ViaFacet$ProtocolBased.createPacket(ViaFacet.java:163) ~[?:?]
        at net.titanvale.titanapi.libs.kyori.adventure.platform.viaversion.ViaFacet$Chat.sendMessage(ViaFacet.java:183) ~[?:?]
        at net.titanvale.titanapi.libs.kyori.adventure.platform.viaversion.ViaFacet$Chat.sendMessage(ViaFacet.java:176) ~[?:?]
        at net.titanvale.titanapi.libs.kyori.adventure.platform.facet.FacetAudience.sendMessage(FacetAudience.java:161) ~[?:?]
        at net.titanvale.titanapi.libs.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[?:?]
        at net.titanvale.titanapi.libs.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[?:?]
        at net.titanvale.titanmessages.bukkit.command.LangCommand.onCommand(LangCommand.java:49) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more```

When player version is 1.12-1.15.2 all works fine.
I tested other ViaVersion versions (3.2.0 and 3.0.0).
I don't know if it Adventure or ViaVersion problem and I decided to first report it here.

**Comment by zml2008** [comment]
You're relocating netty, that will break viaversion, so don't do that. MC already has a copy of netty.
