### ISSUE TITLE
Unable to handle Empty Hover Event Value/Contents Array

### ISSUE THREAD

**Issue by LOOHP** [KyoriPowered/adventure#414]
Weirdly enough, vanilla Minecraft actually accepts a json string like this as a valid chat component.
```json
{"text": "hello", "hoverEvent":{"action":"show_text","value":[]}}
```
AND
```json
{"text": "hello", "hoverEvent":{"action":"show_text","contents":[]}}
```
Which in game, the whole hoverEvent would just be ignored.
But with Adventure, it'll not know what to do/throw an error.
```
[02:25:32 INFO]: com.google.gson.JsonParseException: Don't know how to turn [] into a Component
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.notSureHowToDeserialize(ComponentSerializerImpl.java:262) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:92) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:75) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:155) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:98) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:53) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:161) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:75) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:852) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:801) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:773) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:101) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
[02:25:32 INFO]:        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:44) ~[Paper-Server-reobf.jar:git-Paper-"416ec98"]
```
An extra piece of information,
```json
[]
```
is not a valid component as expected, so accepting (and then ignoring) empty arrays is just a special case for Components in hoverEvents, not everywhere.

**Comment by LOOHP** [comment]
I thought about doing a PR to solve this issue, but I am unsure how Adventure would want to do it. Create a different ShowTextSerializer maybe? Or maybe modify the existing ComponentSerializerImpl?
