### ISSUE TITLE
ClickEvent action causes `java.lang.UnsupportedOperationException: null` error

### ISSUE THREAD

**Issue by LoneDev6** [KyoriPowered/adventure#801]
Seems that this particular JSON text causes a `java.lang.UnsupportedOperationException: null` error.
The JSON is from Quickshop plugin which I'm not the author of.
(shaded lib stacktrace)
```
[00:34:20] [Server thread/ERROR]: [ItemsAdder] Unhandled exception occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: null
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:206) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:161) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[LoneLibs.jar:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:87) ~[LoneLibs.jar:?]
	at lonelibs.net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[LoneLibs.jar:?]
	at dev.lone.itemsadder.NMS.aE.aE.a(SourceFile:77) ~[ItemsAdder_3.2.2-beta5.jar:?]
	at dev.lone.itemsadder.main.jS.f(SourceFile:115) ~[ItemsAdder_3.2.2-beta5.jar:?]
	at dev.lone.itemsadder.main.jM.onPacketSending(SourceFile:203) ~[ItemsAdder_3.2.2-beta5.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:470) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2812) ~[purpur-1.19.jar:git-Purpur-1716]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2794) ~[purpur-1.19.jar:git-Purpur-1716]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:2774) ~[purpur-1.19.jar:git-Purpur-1716]
	at org.maxgamer.quickshop.chat.platform.minedown.BungeeQuickChat.send(BungeeQuickChat.java:66) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.sendShopInfo(SimpleShopManager.java:1248) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.listener.PlayerListener.postTrade(PlayerListener.java:199) ~[QuickShop-5.1.0.9.jar:?]
	at org.maxgamer.quickshop.listener.PlayerListener.onClick(PlayerListener.java:92) ~[QuickShop-5.1.0.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1716]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.19.jar:git-Purpur-1716]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.19.jar:git-Purpur-1716]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1875) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.19.jar:git-Purpur-1716]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1716]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Docs reference used
https://docs.adventure.kyori.net/serializer/index.html?highlight=gsoncomponentserializer

JSON:
```{"extra":[{"color":"dark_aqua","text":"| "},{"color":"gray","text":"������"},{"color":"dark_gray","text":"| "},{"color":"yellow","extra":[{"hoverEvent":{"action":"show_item","value":[{"text":"{Count:1b,id:\"minecraft:elytra\",tag:{Damage:0}}"}]},"translate":"item.minecraft.elytra"}],"text":""},{"color":"yellow","text":"  "},{"text":" "},{"color":"aqua","clickEvent":{"action":"run_command","value":"/qs silentpreview 9556ef40-cd0a-4556-953e-057acdade9ce"},"text":"[������ �̸�����]"}],"text":""}```

Test code:
```java
GsonComponentSerializer.gson().deserialize("{\"extra\":[{\"color\":\"dark_aqua\",\"text\":\"| \"},{\"color\":\"gray\",\"text\":\"������\"},{\"color\":\"dark_gray\",\"text\":\"| \"},{\"color\":\"yellow\",\"extra\":[{\"hoverEvent\":{\"action\":\"show_item\",\"value\":[{\"text\":\"{Count:1b,id:\\\"minecraft:elytra\\\",tag:{Damage:0}}\"}]},\"translate\":\"item.minecraft.elytra\"}],\"text\":\"\"},{\"color\":\"yellow\",\"text\":\"  \"},{\"text\":\" \"},{\"color\":\"aqua\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/qs silentpreview 9556ef40-cd0a-4556-953e-057acdade9ce\"},\"text\":\"[������ �̸�����]\"}],\"text\":\"\"}");
```

adventure-text-serializer-gson: 4.12.0-SNAPSHOT
adventure-api: 4.12.0-SNAPSHOT
adventure-platform-bukkit: 4.1.1

**Comment by kezz** [comment]
Looks like badly formed JSON to me. Head into the Discord if you need more support.

**Comment by LoneDev6** [comment]
Thanks a lot, I contacted the original user who reported the issue.
Have a nice day

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/183446280-590bd180-b204-490d-a9c6-8e17df3e3279.png)

This is the solution, the data wasn't malformed.
```java
GsonComponentSerializer.builder().legacyHoverEventSerializer(NBTLegacyHoverEventSerializer.get()).build()
```
